### ISSUE TITLE
I'd like to contribute

### ISSUE THREAD

**Issue by kaykyr** [ostix360/Quiet_STaR#1]
Hello! I'd like to contribute with this project! We can think together to provide the solutions we need to finish this code. Can you please contact me at Telegram: @kaykyr?

**Comment by ostix360** [comment]
Hi!
Do you have discord? otherwise I'll contact you at telegram

**Comment by kaykyr** [comment]
Let's continue with Telegram. I have a small server with RTX 4090 + RTX 3090 = 48GB VRAM + 64GB DDR5 RAM, you can definitely use this to proceed with tests.

I have used the original Quet-STaR and implemented Mixture of Experts on linear layers, I think now my training is proceeding really good, I'd like to share full code with you to take a look.

Please, contact me at Telegram.

**Comment by kaykyr** [comment]
Please take a look at: https://github.com/kaykyr/Aura-QSTaR-16x7B
